# Generated by Django 3.0.9 on 2021-01-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='numero_tarjeta',
            field=models.CharField(max_length=16),
        ),
    ]
